server:
  port: 8000

eureka:
  client:
    fetch-registry: true  # 유레카 클라이언트 활성화
    register-with-eureka: true  # 유레카 클라이언트 활성화
    service-url:
      defaultZone: http://localhost:8761/eureka # 유레카 클라이언트로 등록

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - name: DefaultFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        # 날짜
        - id: user-date
          uri: lb://eurekaClientUser
          predicates:
          - Path=/user/date/**
          - Before=2022-07-20T17:42:47.789-07:00
          - After=2017-01-20T17:42:47.789-07:00

        # 쿠키
        - id: user-cookie
          uri: lb://eurekaClientUser
          predicates:
            - Path=/user/cookie/**
            - Cookie=valid, kakao

        # 메서드
        - id: user-method
          uri: lb://eurekaClientUser
          predicates:
            - Path=/user/method/**
            - Method=GET,POST

        - id: user-add
          uri: lb://eurekaClientUser
          predicates:
          - Path=/user/add
          filters:
          - AddRequestHeader=token, 123456
          - AddResponseHeader=authenticated, yes

        - id: order-rewrite
          uri: http://localhost:8081
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/?(?<segment>.*), /$\{segment}
            - name: CustomAuthFilter
              args:
                baseMessage: args Test

#        - id: dynamic-routing
#          uri: lb://{serviceid}
#          predicates:
#          - Path=/{serviceid}
#          filters:
#          - RewritePath=/.*/(?<api>.*),/${api}

# localhost:8000/user/info -> localhost:8080/user/info
# localhost:8000/order/info -> localhost:8081/order/info
